version: '3.3'

services:
  app:
    image: sipf/tps:0.1.3
    container_name: app
    ports: 
      - 80:3000
    environment:
      - APP_HOST=beta.demarches-simplifiees.gov.pf
      - DB_DATABASE="dspf-prod"
      - DB_HOST="10.8.0.41"
      - DB_USERNAME="sysadmin"
      - DB_PASSWORD="sysadmin"
      - CARRIERWAVE_CACHE_DIR=/app/tmp
    volumes:
      - datafiles:/app/storage
      - tempfiles:/app/tmp
      #----- to set the timezone to the same as the host
      - /etc/localtime:/etc/localtime:ro
    networks:
      - tps-network

  worker:
    image: sipf/tps:0.1.3
    command: rails jobs:work
    container_name: worker
    environment:
      - APP_HOST=beta.demarches-simplifiees.gov.pf
      - DB_DATABASE="dspf-prod"
      - DB_HOST="10.8.0.41"
      - DB_USERNAME="sysadmin"
      - DB_PASSWORD="sysadmin"

#------ Mailjet Christian
#      - MAILJET_API_KEY=6f6189d645e21e65d93a323efdac07a4
#      - MAILJET_SECRET_KEY=e865ed7fa5a9fa9a9e10a203ab4765c9

#------ Mailjet Leo
      - MAILJET_API_KEY=dc48bab177a12dfd8e416550599b2e0b
      - MAILJET_SECRET_KEY=79b592075e48a83c935e601dbe40d916
    volumes:
      #----- to set the timezone to the same as the host
      - /etc/localtime:/etc/localtime:ro
    networks:
      - tps-network

volumes:
  datafiles:
    driver: local
    driver_opts:
      type: none
      device: $PWD/data
      o: bind
  tempfiles:
    driver: local
    driver_opts:
      type: none
      device: $PWD/tmp
      o: bind

networks:
  tps-network:
    driver: bridge
    ipam:
      config:
        - subnet: 10.5.0.0/24
